# Generated by Django 2.1.7 on 2019-03-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default=1, max_length=20, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('Peso', 'Peso'), ('Nº Productos', 'Nº Productos')], default=1, max_length=20, verbose_name='Tipo de Restricción')),
                ('min_value', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor Mínimo')),
                ('max_value', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Valor Máximo')),
            ],
            options={
                'verbose_name': 'Restricción',
                'verbose_name_plural': 'Restricciones',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default=1, max_length=20, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('duration', models.PositiveIntegerField(blank=True, default=0, verbose_name='Tiempo de Entrega')),
                ('constraints', models.ManyToManyField(blank=True, related_name='shipping_constraints', to='shipping_app.Constraint', verbose_name='Restricciones')),
            ],
            options={
                'verbose_name': 'Método de Envío',
                'verbose_name_plural': 'Métodos de Envío',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping_app.Country')),
            ],
            options={
                'verbose_name': 'Comunidad Autonónoma',
                'verbose_name_plural': 'Comunidades Autónomas',
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default=1, max_length=20, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default=1, max_length=20, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('postal_code', models.TextField(blank=True, null=True, verbose_name='Código Postal')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_zone', to='shipping_app.Country', verbose_name='País')),
                ('methods', models.ManyToManyField(blank=True, related_name='shipping_methods', to='shipping_app.Method', verbose_name='Métodos de Envio')),
                ('province', models.ManyToManyField(blank=True, related_name='province_zone', to='shipping_app.Province', verbose_name='Provincia')),
                ('region', models.ManyToManyField(blank=True, related_name='region_zone', to='shipping_app.Region', verbose_name='Comunidad Autónoma')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping_app.Region'),
        ),
        migrations.AddField(
            model_name='method',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_shipper', to='shipping_app.Shipper', verbose_name='Transportista'),
        ),
    ]
