# Generated by Django 2.2 on 2019-04-30 17:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'db_table': 'container',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('priority', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Prioridad')),
                ('entry_date', models.DateTimeField(verbose_name='Fecha de Entrada')),
                ('exit_date', models.DateTimeField(verbose_name='Fecha de Entrada')),
                ('sla', models.FileField(upload_to='', verbose_name='Service Level Agreement')),
                ('min_humidity', models.PositiveIntegerField(default=23, verbose_name='Hum. Mínima')),
                ('max_humidity', models.PositiveIntegerField(default=23, verbose_name='Hum. Máxima')),
                ('max_temperature', models.IntegerField(default=23, verbose_name='Temp. Máxima')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Cerrada', max_length=7, verbose_name='Estado')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('humidity', models.PositiveIntegerField(default=23, verbose_name='Humedad')),
                ('temperature', models.IntegerField(default=23, verbose_name='Temperatura')),
                ('max_containers', models.PositiveIntegerField(default=4, verbose_name='Capacidad Máxima')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='RoomMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado')], default='Disponible', max_length=10, verbose_name='Estado')),
                ('x', models.PositiveIntegerField(verbose_name='Eje X')),
                ('y', models.PositiveIntegerField(verbose_name='Eje Y')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_map', to='storage_go_app.Room', verbose_name='Mapa')),
            ],
            options={
                'verbose_name': 'Mapa de Sala',
                'verbose_name_plural': 'Mapas de Sala',
                'db_table': 'room_map',
            },
        ),
        migrations.CreateModel(
            name='MoveTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_task_container', to='storage_go_app.Container', verbose_name='Contenedor')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_room', to='storage_go_app.Room', verbose_name='Sala destino')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_room', to='storage_go_app.Room', verbose_name='Sala origen')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_task_worker', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Tarea de Movimiento',
                'verbose_name_plural': 'Tareas de Movimiento',
                'db_table': 'move_task',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=50, verbose_name='Máquina')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_task_room', to='storage_go_app.Room', verbose_name='Sala')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_task_worker', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Tarea de Mantenimiento',
                'verbose_name_plural': 'Tareas de Mantenimiento',
                'db_table': 'maintenance_task',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='container_product', to='storage_go_app.Product', verbose_name='Producto'),
        ),
    ]
