# Generated by Django 2.2 on 2019-05-30 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_go_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Trabajando')),
            ],
            options={
                'verbose_name': 'Usuario Activo',
                'verbose_name_plural': 'Usuarios Activos',
                'db_table': 'active_user',
                'default_permissions': (),
            },
        ),
    ]
