# Generated by Django 2.2 on 2019-04-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_go_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movetask',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_task_container', to='storage_go_app.Container', verbose_name='Contenedor'),
        ),
    ]
