# Generated by Django 2.2 on 2019-05-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_go_app', '0002_auto_20190430_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Módulo', 'Módulo'), ('Modelo', 'Modelo'), ('Objecto', 'Objecto'), ('Atributo', 'Atributo')], default=1, max_length=10)),
                ('action', models.CharField(choices=[('Ver', 'Ver'), ('Crear', 'Crear'), ('Modificar', 'Modificar'), ('Borrar', 'Borrar')], default=1, max_length=10)),
                ('module', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50, null=True)),
                ('object', models.CharField(max_length=50, null=True)),
                ('attribute', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Permiso Personalizado',
                'verbose_name_plural': 'Permisos Personalizados',
            },
        ),
    ]
