# Generated by Django 2.2 on 2019-05-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_go_app', '0003_custompermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompermission',
            name='module',
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='action',
            field=models.CharField(choices=[('Ver', 'Ver'), ('Crear', 'Crear'), ('Modificar', 'Modificar'), ('Borrar', 'Borrar')], default=1, max_length=10, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='attribute',
            field=models.CharField(max_length=50, null=True, verbose_name='Attributo'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='model',
            field=models.CharField(max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='object',
            field=models.CharField(max_length=50, null=True, verbose_name='Objeto'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='type',
            field=models.CharField(choices=[('Modelo', 'Modelo'), ('Objeto', 'Objeto'), ('Atributo', 'Atributo')], default=1, max_length=10, verbose_name='Tipo'),
        ),
    ]
