# Generated by Django 2.2 on 2019-06-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_go_app', '0003_auto_20190601_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='entry_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Entrada'),
        ),
        migrations.AlterField(
            model_name='product',
            name='exit_date',
            field=models.DateField(verbose_name='Fecha de Salida'),
        ),
    ]
